server:
  port: 8080

spring:

  application:
    name: Java-SpringBoot-JPA

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1;
      connection-timeout: 20000
